name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{hashFiles('pnpm-lock.yaml')}}
          restore-keys: node_modules-

      - run: pnpm install --frozen-lockfile
      - run: pnpm test
